INFO       - 2023-07-10 14:37:22,526 - client          : logging in using static token
INFO       - 2023-07-10 14:37:23,778 - gateway         : Shard ID None has connected to Gateway (Session ID: 32c7f4f607d757ee02829b57a46e8815).
WARNING    - 2023-07-10 14:38:14,899 - gateway         : Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 30, in execute
    self.conn.rollback()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 496, in rollback
    self._cmysql.rollback()

WARNING    - 2023-07-10 14:38:24,951 - gateway         : Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:38:34,970 - gateway         : Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:38:45,007 - gateway         : Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:38:55,018 - gateway         : Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:39:05,040 - gateway         : Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:39:15,118 - gateway         : Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:39:25,143 - gateway         : Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 30, in execute
    self.conn.rollback()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 496, in rollback
    self._cmysql.rollback()

WARNING    - 2023-07-10 14:39:35,179 - gateway         : Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:39:45,205 - gateway         : Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:39:55,234 - gateway         : Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:40:05,263 - gateway         : Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:40:15,308 - gateway         : Shard ID None heartbeat blocked for more than 130 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:40:25,347 - gateway         : Shard ID None heartbeat blocked for more than 140 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 45, in on_ready
    print(f"{problem['name']} OK")

WARNING    - 2023-07-10 14:40:35,372 - gateway         : Shard ID None heartbeat blocked for more than 150 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 45, in on_ready
    print(f"{problem['name']} OK")

WARNING    - 2023-07-10 14:40:45,398 - gateway         : Shard ID None heartbeat blocked for more than 160 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:40:55,423 - gateway         : Shard ID None heartbeat blocked for more than 170 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:41:05,524 - gateway         : Shard ID None heartbeat blocked for more than 180 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:41:15,596 - gateway         : Shard ID None heartbeat blocked for more than 190 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:41:25,620 - gateway         : Shard ID None heartbeat blocked for more than 200 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:41:35,650 - gateway         : Shard ID None heartbeat blocked for more than 210 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:41:45,669 - gateway         : Shard ID None heartbeat blocked for more than 220 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:41:55,788 - gateway         : Shard ID None heartbeat blocked for more than 230 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:42:05,814 - gateway         : Shard ID None heartbeat blocked for more than 240 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:42:15,849 - gateway         : Shard ID None heartbeat blocked for more than 250 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:42:25,878 - gateway         : Shard ID None heartbeat blocked for more than 260 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:42:35,969 - gateway         : Shard ID None heartbeat blocked for more than 270 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:42:45,993 - gateway         : Shard ID None heartbeat blocked for more than 280 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:42:56,082 - gateway         : Shard ID None heartbeat blocked for more than 290 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:43:06,105 - gateway         : Shard ID None heartbeat blocked for more than 300 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 30, in execute
    self.conn.rollback()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 496, in rollback
    self._cmysql.rollback()

WARNING    - 2023-07-10 14:43:16,124 - gateway         : Shard ID None heartbeat blocked for more than 310 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:43:26,145 - gateway         : Shard ID None heartbeat blocked for more than 320 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:43:36,172 - gateway         : Shard ID None heartbeat blocked for more than 330 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:43:46,315 - gateway         : Shard ID None heartbeat blocked for more than 340 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:43:56,344 - gateway         : Shard ID None heartbeat blocked for more than 350 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:44:06,369 - gateway         : Shard ID None heartbeat blocked for more than 360 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:44:16,455 - gateway         : Shard ID None heartbeat blocked for more than 370 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:44:26,478 - gateway         : Shard ID None heartbeat blocked for more than 380 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:44:36,497 - gateway         : Shard ID None heartbeat blocked for more than 390 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:44:46,524 - gateway         : Shard ID None heartbeat blocked for more than 400 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:44:56,564 - gateway         : Shard ID None heartbeat blocked for more than 410 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:45:06,614 - gateway         : Shard ID None heartbeat blocked for more than 420 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:45:16,666 - gateway         : Shard ID None heartbeat blocked for more than 430 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:45:26,707 - gateway         : Shard ID None heartbeat blocked for more than 440 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:45:36,715 - gateway         : Shard ID None heartbeat blocked for more than 450 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:45:46,746 - gateway         : Shard ID None heartbeat blocked for more than 460 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 45, in on_ready
    print(f"{problem['name']} OK")

WARNING    - 2023-07-10 14:45:56,769 - gateway         : Shard ID None heartbeat blocked for more than 470 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:46:06,847 - gateway         : Shard ID None heartbeat blocked for more than 480 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:46:16,922 - gateway         : Shard ID None heartbeat blocked for more than 490 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:46:26,945 - gateway         : Shard ID None heartbeat blocked for more than 500 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:46:37,025 - gateway         : Shard ID None heartbeat blocked for more than 510 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:46:47,047 - gateway         : Shard ID None heartbeat blocked for more than 520 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 30, in execute
    self.conn.rollback()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 496, in rollback
    self._cmysql.rollback()

WARNING    - 2023-07-10 14:46:57,058 - gateway         : Shard ID None heartbeat blocked for more than 530 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:47:07,136 - gateway         : Shard ID None heartbeat blocked for more than 540 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:47:17,161 - gateway         : Shard ID None heartbeat blocked for more than 550 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:47:27,173 - gateway         : Shard ID None heartbeat blocked for more than 560 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:47:37,203 - gateway         : Shard ID None heartbeat blocked for more than 570 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:47:47,240 - gateway         : Shard ID None heartbeat blocked for more than 580 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:47:57,267 - gateway         : Shard ID None heartbeat blocked for more than 590 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:48:07,297 - gateway         : Shard ID None heartbeat blocked for more than 600 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:48:17,377 - gateway         : Shard ID None heartbeat blocked for more than 610 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:48:27,405 - gateway         : Shard ID None heartbeat blocked for more than 620 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:48:37,521 - gateway         : Shard ID None heartbeat blocked for more than 630 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:48:47,547 - gateway         : Shard ID None heartbeat blocked for more than 640 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:48:57,619 - gateway         : Shard ID None heartbeat blocked for more than 650 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:49:07,641 - gateway         : Shard ID None heartbeat blocked for more than 660 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:49:17,670 - gateway         : Shard ID None heartbeat blocked for more than 670 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:49:27,801 - gateway         : Shard ID None heartbeat blocked for more than 680 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:49:37,825 - gateway         : Shard ID None heartbeat blocked for more than 690 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:49:47,846 - gateway         : Shard ID None heartbeat blocked for more than 700 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 30, in execute
    self.conn.rollback()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 496, in rollback
    self._cmysql.rollback()

WARNING    - 2023-07-10 14:49:57,927 - gateway         : Shard ID None heartbeat blocked for more than 710 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:50:08,045 - gateway         : Shard ID None heartbeat blocked for more than 720 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:50:18,074 - gateway         : Shard ID None heartbeat blocked for more than 730 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 56, in write
    self.execute(sql, id, index, name, rating)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:50:28,107 - gateway         : Shard ID None heartbeat blocked for more than 740 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:50:38,132 - gateway         : Shard ID None heartbeat blocked for more than 750 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:50:48,165 - gateway         : Shard ID None heartbeat blocked for more than 760 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:50:58,199 - gateway         : Shard ID None heartbeat blocked for more than 770 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 28, in execute
    self.conn.commit()
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 490, in commit
    self._cmysql.commit()

WARNING    - 2023-07-10 14:51:08,231 - gateway         : Shard ID None heartbeat blocked for more than 780 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

WARNING    - 2023-07-10 14:51:18,317 - gateway         : Shard ID None heartbeat blocked for more than 790 seconds.
Loop thread traceback (most recent call last):
  File "D:\Project\Lockout-Bot2.0\main.py", line 68, in <module>
    main()
  File "D:\Project\Lockout-Bot2.0\main.py", line 65, in main
    client.run(settings.BOT_TOKEN, root_logger=True)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\marve\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Project\Lockout-Bot2.0\main.py", line 44, in on_ready
    conn.write(problem['contestId'], problem['index'], problem['name'], problem['rating'], problem['tags'])
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 62, in write
    self.execute(sql, name, tag)
  File "D:\Project\Lockout-Bot2.0\data\connect.py", line 27, in execute
    self.cursor.execute(sql, args)
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "D:\Project\Lockout-Bot2.0\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 611, in cmd_query
    self._cmysql.query(

